twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # ligne 2 et 3 doivent avoir la même tabulation si non ca marche pas
    
# nous indiquons que tous nos formulaires utilisent maintenant les classes de bootstrap 5
when@test:
    twig:
        strict_variables: true
